function init()
	g_shaders.createShader("map_default", "/shaders/map_default_vertex", "/shaders/map_default_fragment")
	g_shaders.createShader("map_rainbow", "/shaders/map_rainbow_vertex", "/shaders/map_rainbow_fragment")
	g_shaders.addTexture("map_rainbow", "/images/shaders/rainbow.png")
	g_shaders.createShader("item_black", "/shaders/default", "/shaders/item_black_fragment")
	g_shaders.createOutfitShader("outfit_default", "/shaders/outfit_default_vertex", "/shaders/outfit_default_fragment")
	g_shaders.createOutfitShader("outline_default", "/shaders/default", "/shaders/outline")
	g_shaders.createOutfitShader("outline_red", "/shaders/outline_red_vertex", "/shaders/outline_red_fragment")
	g_shaders.createOutfitShader("outfit_rainbow", "/shaders/outfit_rainbow_vertex", "/shaders/outfit_rainbow_fragment")
	g_shaders.addTexture("outfit_rainbow", "/images/shaders/rainbow.png")
	g_shaders.createOutfitShader("ShaderLightBlue", "/shaders/outline/outline_vertex", "/shaders/outline/outline_light_blue_fragment")
	g_shaders.createOutfitShader("ShaderBlue", "/shaders/outline/outline_vertex", "/shaders/outline/outline_blue_fragment")
	g_shaders.createOutfitShader("ShaderRed", "/shaders/outline/outline_vertex", "/shaders/outline/outline_red_fragment")
	g_shaders.createOutfitShader("ShaderDarkRed", "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_red_fragment")
	g_shaders.createOutfitShader("ShaderPurple", "/shaders/outline/outline_vertex", "/shaders/outline/outline_purple_fragment")
	g_shaders.createOutfitShader("ShaderWhite", "/shaders/outline/outline_vertex", "/shaders/outline/outline_white_fragment")
	g_shaders.createOutfitShader("ShaderDarkGreen", "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_green_fragment")
	g_shaders.createOutfitShader("ShaderForestGreen", "/shaders/outline/outline_vertex", "/shaders/outline/outline_forest_green_fragment")
	g_shaders.createOutfitShader("ShaderMud", "/shaders/outline/outline_vertex", "/shaders/outline/outline_mud_fragment")
	g_shaders.createOutfitShader("ShaderLightBlueStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_light_blue_static_fragment")
	g_shaders.createOutfitShader("ShaderBlueStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_blue_static_fragment")
	g_shaders.createOutfitShader("ShaderRedStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_red_static_fragment")
	g_shaders.createOutfitShader("ShaderDarkRedStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_red_static_fragment")
	g_shaders.createOutfitShader("ShaderPurpleStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_purple_static_fragment")
	g_shaders.createOutfitShader("ShaderWhiteStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_white_static_fragment")
	g_shaders.createOutfitShader("ShaderRage", "/shaders/outline/outline_vertex", "/shaders/outline/rage_shader")
	g_shaders.createOutfitShader("ShaderFreeze", "/shaders/outline/outline_vertex", "/shaders/outline/freeze_shader")
	g_shaders.createOutfitShader("ShaderGreen", "/shaders/outline/outline_vertex", "/shaders/outline/outline_green_fragment")
	g_shaders.createOutfitShader("ShaderGreenStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_green_static_fragment")
	g_shaders.createOutfitShader("ShaderYellow", "/shaders/outline/outline_vertex", "/shaders/outline/outline_yellow_fragment")
	g_shaders.createOutfitShader("ShaderYellowStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_yellow_static_fragment")
	g_shaders.createOutfitShader("ShaderCreatureHighlight", "/shaders/outline/outline_vertex", "/shaders/outline/creature_highlight")
	g_shaders.createOutfitShader("ShaderGreenOutfit", "/shaders/outline/outline_vertex", "/shaders/outline/green_outfit")
	g_shaders.createOutfitShader("ShaderPurpleOutfit", "/shaders/outline/outline_vertex", "/shaders/outline/purple_outfit")
	g_shaders.createOutfitShader("ShaderDarkGreenStatic", "/shaders/outline/outline_vertex", "/shaders/outline/outline_dark_green_static_fragment")
end

function terminate()
end
